Feature flex changes
TaskarCenterAtUW/TDEI-template-flex-datasvc-ts pull request #28
Opened 2023-06-15 10:53 UTC by MashB

Feedback changes

2023-06-15 14:23 UTC, sureshgaussian requested changes
Please update the description of PR with what the changes are. 'Feedback changes' is too vague.

2023-06-21 13:07 UTC, susrisha submitted a review, later dismissed

2023-06-21 14:33 UTC, sureshgaussian requested changes

2023-06-21 14:33 UTC, sureshgaussian commented on test/test-case-enumeration.md
> +| Controller | Create Flex File | Functional| When provided null body | Expect to return HTTP status 500 |:white_check_mark:|
should the return status be 400?

2023-06-22 14:19 UTC, sureshgaussian approved these changes
PR approved.

2023-06-22 15:54 UTC, merged