Refactor event bus
TaskarCenterAtUW/TDEI-template-flex-datasvc-ts pull request #34
Opened 2023-08-07 13:59 UTC by iAKM

2023-08-08 04:21 UTC, MashB commented
Need to add storage connection integration test

2023-08-09 14:06 UTC, iAKM commented
added storage check in integration test

2023-08-10 05:27 UTC, MashB requested changes

2023-08-10 05:27 UTC, MashB commented on test/integration/flex.integration.test.ts
> +    test('Verifying the service can access File Storage with file URL ', async () => {
Can we try listing the file of flex container , this validates container exists and connection establishment is complete.

2023-08-10 11:22 UTC, MashB approved these changes

2023-08-17 14:42 UTC, merged